---
# Included tasks for galileo_ansible_role
- include_tasks: validate.yml
- include_tasks: answerfile.yml
- include_tasks: RedHat.yml
  when: ansible_distribution == "RedHat"
- include_tasks: registration.yml
