---
# handlers file for galileo_ansible_role
- name: "Cleanup RPM"
  file:
    path: '{{ galileo_ansible_role_rpm_path }}/{{ galileo_ansible_role_comm_rpm_file }}'
    state: absent

- name: "Cleanup Answer File"
  file:
    path: '/tmp/gpe-agent-comm.answer'
    state: absent